### ISSUE TITLE
Group name

### ISSUE THREAD

**Issue by BigOHenry** [WebChemistry/forms-multiplier#10]
Hello,
in the Multiplier container there is no group name set in the form with:
`$form->addGroup('GroupName');`

So in the template when i call this: `$control->getOption('group');` i get error there is no group option.

Is any way to add this feature? 

Thank you :)

**Comment by MartkCz** [comment]
Can you try dev-master, please? I do not know if I understood it

**Comment by BigOHenry** [comment]
Yeah, thats it. Works great. Thank you :-)
