### ISSUE TITLE
Ajaxification

### ISSUE THREAD

**Issue by Mart78** [WebChemistry/forms-multiplier#15]
Is there some way how to ajaxify adding/removing of rows?

**Comment by MartkCz** [comment]
This could help
```php
			$multiplier->addRemoveButton(null, function (SubmitButton $submitter) {
				$submitter->onSubmit[] = function () {
				        // redraw snippet
				};
				$submitter->setHtmlAttribute('class', 'ajax');
			});
```

**Comment by Mart78** [comment]
throws MemberAccessException: Cannot read an undeclared property Nette\Forms\Controls\SubmitButton::$onSubmit.

**Comment by MartkCz** [comment]
Yeah sorry, I mean onClick. Edit the code

**Comment by Mart78** [comment]
Not working, ajax css class is not appended to html element
`		$itemsMultiplier->addRemoveButton('Smazat', function (Nette\Forms\Controls\SubmitButton $submitter) {
				$submitter->onClick[] = function () {
				        $this->redrawControl('variantsCont');
				};
				$submitter->setHtmlAttribute('class', 'ajax');
			});`

**Comment by MartkCz** [comment]
If you use manual render you must add class into a template.

**Comment by Mart78** [comment]
OK, now it working. Ajaxified adding/removing of rows. Thanks! Díky :)
