### ISSUE TITLE
Grouping form submit with multiplier buttons

### ISSUE THREAD

**Issue by llsm** [WebChemistry/forms-multiplier#24]
Hi,
i have whole form submit button after multiplier buttons and form renders them all (buttons) together in one group instead separetly, is there any workaround besides manual form render?

I have tried to use form groups, but that messed up multipliers adding new fields order. Which probably second issue ; )

**Comment by MartkCz** [comment]
It depends on form renderer. You must rewrite DefaultFormRenderer class

**Comment by llsm** [comment]
Thanks for reply and great component. Yes, thats one option. On the other hand, this problem will occur probably with all renderers, for example i use Boostrap 4 renderer from aleswita, which of course has the same problem as Nette default one. From my perspective Multiplier creates this problem and should solve it on its own, because this behavior will hardly be desireable for anyone.

**Comment by MartkCz** [comment]
Multiplier doesn't affect rendering only changes the number of components. If you add 2 buttons in a row

```php
$form->addSubmit('first');
$form->addSubmit('second');
```
Renderers (default and from aleswita) renders them in a row.
