### ISSUE TITLE
Wrong adding order when 2 multipliers in form group

### ISSUE THREAD

**Issue by llsm** [WebChemistry/forms-multiplier#25]
Hi, 
i have two multipliers in one form group and when i try to add field in first one, field is after second multiplier as shown on image:

![multiplier](https://user-images.githubusercontent.com/11448903/38876039-fbc10998-425b-11e8-964d-681d305bcf62.PNG)

**Comment by MartkCz** [comment]
Can you send me code of form, please?

**Comment by llsm** [comment]
$form = new \Nette\Application\UI\Form;

		$form->addText('name', 'jméno')
				->addRule($form::FILLED, 'Vyplňte jméno');
		$form->addText('surname', 'příjmení')
				->addRule($form::FILLED, 'Vyplňte příjmení');

		$copies = 1;
		$maxCopies = 3;
		$mailMultiplier = $form->addMultiplier('mailMultiplier', function (\Nette\Forms\Container $container, \Nette\Application\UI\Form $form) {
			$container->addText('mail', 'kontaktní e-mail')
					->setType('email')
					->setRequired('Zadejte prosím e-mail.')
					->addRule($form::EMAIL, 'Zkontrolujte překlepy v e-mailu, zadaná adresa není platná');
		}, $copies, $maxCopies);
		$mailMultiplier->addCreateButton('Zadat další e-mail');
		$mailMultiplier->addRemoveButton('Odstranit e-mail');


		$telMultiplier = $form->addMultiplier('telMultiplier', function (\Nette\Forms\Container $container) {
			$container->addText('tel', 'kontaktní telefon')
					->setRequired('Vyplňte telefonní číslo');
		}, $copies, $maxCopies);
		$telMultiplier->addCreateButton('Zadat další telefon');
		$telMultiplier->addRemoveButton('Odstranit telefon');


		$form->addSubmit('save', 'Odeslat');
		$form->onSuccess[] = [$this, 'processForm'];

		return $form;

**Comment by MartkCz** [comment]
Can you try version 3.0.0?

**Comment by llsm** [comment]
Same issue + messes up add/delete buttons labels on second element of multiplier, which works fine in 2.0.4

**Comment by llsm** [comment]
Standard latte {control form} macro

**Comment by MartkCz** [comment]
Sorry for delay, I had to overwrite the algorithm.
