### ISSUE TITLE
Missing "getCreateButtons" method

### ISSUE THREAD

**Issue by LuckyLuky** [WebChemistry/forms-multiplier#27]
Hi, 

I get this error: `Call to undefined method WebChemistry\Forms\Controls\Multiplier::getCreateButtons(), did you mean addCreateButton()?` when using `btnCreate` macro. 
It looks like the `getCreateButtons` method isn't anywhere in the package.

**Comment by MartkCz** [comment]
You must use dev-master https://github.com/WebChemistry/forms-multiplier/commit/b1c11b7000c1da818f653f82550e909e303b60aa
