### ISSUE TITLE
Exception of validation

### ISSUE THREAD

**Issue by jAKErCZ** [WebChemistry/forms-multiplier#30]
Hi, I should ask how can I turn off or bypass that when adding a new line using 
`$multiplier->addCreateButton('Add');`
will not validate my entire form?

Something like the classic form of the function?
`->setValidationScope()`

**Comment by MartkCz** [comment]
Try:
```php
$multiplier->addCreateButton('Add', 1, function (WebChemistry\Forms\Controls\Submitter $submitter) {
    $submitter->setValidationScope([]);
});
```

I push commit soon (max 30 minutes), which will allow:
```php
$multiplier->addCreateButton('Add')
    ->setNoValidate();
```

**Comment by MartkCz** [comment]
You can use `$multiplier->addCreateButton('Add')->setValidationScope(...)` too
