### ISSUE TITLE
Missing support for `createOne`

### ISSUE THREAD

**Issue by zeleznypa** [WebChemistry/forms-multiplier#31]
There is method [`createOne` in Kdyby/FormsReplicator](https://github.com/Kdyby/FormsReplicator/blob/master/src/Kdyby/Replicator/Container.php#L210) that allow to work with containers by your own.

In our project there is something like:
```php
<?php

namespace App;

use Nette\Application\UI\Form;

class TestForm extends Form {

	public function __construct() {
		$this->addDynamic('params', function(Container $container) {
			$container->addText('name', 'Název obecného parametru');
		}, 0);
	}

	public function loadParams() {
		$params = [
			'Parametr 1',
			'Parametr 2',
			'Parametr 3',
		];

		foreach ($params as $id => $name) {
			$container = $this['params']->createOne($id);
			$container['name']->caption = $name;
		}
	}

}
```

There is method [`addCopy` in WebChemistry/Multiplier](https://github.com/WebChemistry/forms-multiplier/blob/master/src/Multiplier.php#L248) that work almost same.

But it is protected.

Will it be possible to make this method public by default?

Or,is there any other way for manually adding values in dynamic container and work with each one?

**Comment by MartkCz** [comment]
Can you send whole code? or you can use setDefaults method

**Comment by MartkCz** [comment]
Usage:

```php
	$multiplier->onCreateComponents[] =[$this, 'loadParams'];


	public function loadParams(Multiplier $multiplier) {
		$params = [
			'Parametr 1',
			'Parametr 2',
			'Parametr 3',
		];

		foreach ($params as $name) {
			$container = $multiplier->addCopy();
			$container['name']->caption = $name;
		}
	}
```

**Comment by zeleznypa** [comment]
🙇
