### ISSUE TITLE
Custom container

### ISSUE THREAD

**Issue by kravcik** [WebChemistry/forms-multiplier#35]
I can try prepare PR & test for using custom Container with multiplier. 

![image](https://user-images.githubusercontent.com/10499130/46951896-942eeb80-d089-11e8-9c9c-22362a25581b.png)

Desired result will be definition custom class via extension parameters. Otherwise multiplier use nette container.

```
multiplier:
  containerClass: \Your\Class\Custom;

```

What is your opinion?

**Comment by MartkCz** [comment]
Your PR is welcome

**Comment by kravcik** [comment]
https://github.com/WebChemistry/forms-multiplier/pull/36
