### ISSUE TITLE
multiplier with dependent select

### ISSUE THREAD

**Issue by jarda256** [WebChemistry/forms-multiplier#4]
Hi, I have a little problem. I want to multiply NasExt/DependentSelectBox. But I only got error `Component 'item' is not attached to 'Nette\Forms\Form'.` Thanks for any help.

$form->addSelect('event','Event',$firstInput)->setRequired(TRUE)->setPrompt("Select event");

        $form->addDependentSelectBox('site', 'Site:', array($form['event']), function ($values) {
            $data =  new DependentSelectBoxData();
            if (isset($values['event'])) {
                $dataSite = $this->siteFacade->getNamesByEventId($values['event'],$this->locale);
                return $data->setItems($dataSite);
            }else{
                return $data;
            }
        })->setPrompt('- Select Site-')->setRequired()->setDisabledWhenEmpty(TRUE);

        $form->addMultiSelect('members','Members',$members)->setRequired(TRUE);

        $multiplier = $form->addMultiplier('multiplier', function (Nette\Forms\Container $container, Nette\Forms\Form $form) {
            $container->addDependentSelectBox('item', 'Item:', array($form['event']), function ($values) {
                $data =  new DependentSelectBoxData();
                if (isset($values['event'])) {
                    $dataItems = $this->optItemFacade->getOptItemsByEventId($values['event'],$this->locale);
                    return $data->setItems($dataItems);
                }else{
                    return $data;
                }
            })->setPrompt('-Select Item-')->setDisabledWhenEmpty(TRUE);
            $container->addInteger('count','count');
        }, 0, 15);
        $multiplier->addCreateButton('Add');
        $multiplier->addRemoveButton('Remove');

**Comment by MartkCz** [comment]
Can you try dev-master version, please?

**Comment by jarda256** [comment]
Of course. I'll try and give you feedback

**Comment by jarda256** [comment]
Well Dev version works. At least for me. Thanks. When can I expect stable version? If you plan it?
