### ISSUE TITLE
Filling in multiple values

### ISSUE THREAD

**Issue by irkallacz** [WebChemistry/forms-multiplier#5]
Hi. Thanks for good work. I do have one problem. 

I cannot figured out, how to fill in values. For example, when I want to edit previously added values. When I want edit users name and surname I try something like:

// form definition
$form->addMultiplier('users', function (\Nette\Forms\Container $container) {
	        $container->addText('name');
	        $container->addText('surname');
});

//action edit
foreach ($users as $user) {
	            $form['users'][$user->id]['name']->setDefaultValue($user->name);
	            $form['users'][$user->id]['surname']->setDefaultValue($user->surname);
}

But with no luck and the is nothing in documentation.  Thanks.

**Comment by MartkCz** [comment]
When component is attached to presenter, multiplier creates components and new components cannot be added to multiplier. You can use setDefaults in form factory:

```php

class FormFactory {
	
	private $users = [];
	
	public function setUsers(array $users) {
		$this->users = $users;
	}
	
	public function createForm() {
		$form->setDefaults([
			'users' => $this->users,
		]);
	}
	
}

class Presenter {
	
	public function actionDefault() {
		$this->formFactory->setUsers($users);
	}
	
	protected function createComponentForm() {
		return $this->formFactory->createForm();
	} 
	
}

```
