### ISSUE TITLE
Why is method Container::setValues overwriten by Multiplier?

### ISSUE THREAD

**Issue by hrasekj** [WebChemistry/forms-multiplier#6]
Is there any reason to overwrite method `Nette\Forms\Container::setValues()` in Multiplier? Becouse i can't find any.

With `Multiplier::setValues()` i can't use `Form::setDefaults()`. But when i commented out this method it works perfectly.

Is there any use case when you have to use `Multiplier::setControlValues()`?

**Comment by MartkCz** [comment]
Sorry for my late reply, I didn't have enough time. 

Can you try dev?
