### ISSUE TITLE
Add/Remove buttons - how to add class and callback for snippets?

### ISSUE THREAD

**Issue by BigOHenry** [WebChemistry/forms-multiplier#7]
Hello, is there any way how to set on "Add" and "Remove" buttons "class"? I need get multiplier working with ajax. My second question is how to redraw snippet after click on "Add" and "Remove" buttons?

Thank you,
Andrew

**Comment by MartkCz** [comment]
Hi, I can add the options on Sunday.

**Comment by BigOHenry** [comment]
That would be great :-) I could try it too and make PR but i am not much experienced...

**Comment by MartkCz** [comment]
Usage: https://github.com/WebChemistry/forms-multiplier/blob/master/tests/unit/CreateButtonTest.php#L66-L71

**Comment by BigOHenry** [comment]
Thank you very much :-) And what about the redraw snippet? how can i add it?

**Comment by MartkCz** [comment]
You can try add redraw snippet to the callback
