### ISSUE TITLE
With default values remove buttons are missing

### ISSUE THREAD

**Issue by BigOHenry** [WebChemistry/forms-multiplier#9]
Hello,
i have problem with remove buttons with default values. When i create Multiplier with default values, remove buttons are missing...
When i add new container (inputs) with add button and redraw it with ajax all remove buttons are at the form. 

I am not sure, but i think it could be a bug.

**Comment by BigOHenry** [comment]
The problem is in last version...

**Comment by MartkCz** [comment]
Thank you for report! Can you try dev?

**Comment by BigOHenry** [comment]
Its working 👍 Thank you :-)
